services:
  - type: web
    name: space-room
    env: node
    plan: free
    buildCommand: bun install && bun run build
    startCommand: bun run start
    envVars:
      - key: NODE_VERSION
        value: 20
